Modularize portability goo. Work around AIX 5.1L vsnprintf() bug; only affects systems that do not have asprintf() in their libc, which should only be very old systems.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,60 +2,34 @@
 # This configure script written by Brian Callahan <bcallah@devio.us>
 # and released into the Public Domain.
 
+# Figure out C compiler.
+# We can probably assume gcc is available, so it's the failsafe.
 if [ "x$CC" != "x" ] ; then
   cc="$CC"
-  /usr/bin/which $cc > /dev/null 2>&1
-  if [ $? -ne 0 ] ; then
-    echo "C compiler $cc not found."
-    exit 1
-  fi
 else
   /usr/bin/which cc > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
     cc="cc"
   else
-    /usr/bin/which gcc > /dev/null 2>&1
+    /usr/bin/which clang > /dev/null 2>&1
     if [ $? -eq 0 ] ; then
-      cc="gcc"
+      cc="clang"
     else
-      /usr/bin/which clang > /dev/null 2>&1
+      /usr/bin/which gcc > /dev/null 2>&1
       if [ $? -eq 0 ] ; then
-	cc="clang"
+	cc="gcc"
       else
-	/usr/bin/which pcc > /dev/null 2>&1
-	if [ $? -eq 0 ] ; then
-	  cc="pcc"
-	else
-	  echo "No C compiler found."
-	  exit 1
-	fi
+	echo "No C compiler found."
+	echo "Please manually set your C compiler with the CC env variable."
+	exit 1
       fi
     fi
   fi
 fi
 
-printf "Checking for a program named yacc... "
+printf "Checking for yacc... "
 
-cat << EOF > /tmp/checkyacc.y
-%{
-/* This file generated by oyacc configure script.  */
-%}
-
-%%
-
-yacctest:	'='
-	;
-
-%%
-
-int
-main(void)
-{
-	return 0;
-}
-EOF
-
-yacc -o /dev/null /tmp/checkyacc.y > /dev/null 2>&1
+/usr/bin/which yacc > /dev/null 2>&1
 
 if [ $? -eq 0 ] ; then
   echo "yes"
@@ -67,7 +41,63 @@ else
   fix=yyfix
 fi
 
-rm -f /tmp/checkyacc.y
+printf "Checking for reallocarray... "
+
+cat << EOF > /tmp/checkreallocarray.c
+/* This file generated by oyacc configure script.  */
+
+#include <stdlib.h>
+
+int
+main(void)
+{
+	char *tmp;
+
+	tmp = reallocarray(NULL, 1, 1);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkreallocarray /tmp/checkreallocarray.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+  echo "no"
+  needreallocarray="portable/reallocarray.o"
+  cppreallocarray="-DNEED_REALLOCARRAY"
+else
+  echo "yes"
+fi
+
+rm -f /tmp/checkreallocarray /tmp/checkreallocarray.c checkreallocarray.o
+
+printf "Checking for strlcpy... "
+
+cat << EOF > /tmp/checkstrlcpy.c
+/* This file generated by oyacc configure script.  */
+
+#include <string.h>
+
+int
+main(void)
+{
+	(void) strlcpy(NULL, "yacc", 4);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkstrlcpy /tmp/checkstrlcpy.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+  echo "no"
+  needstrlcpy="portable/strlcpy.o"
+  cppstrlcpy="-DNEED_STRLCPY"
+else
+  echo "yes"
+fi
+
+rm -f /tmp/checkstrlcpy /tmp/checkstrlcpy.c checkstrlcpy.o
 
 printf "Checking for asprintf... "
 
@@ -79,10 +109,9 @@ cat << EOF > /tmp/checkasprintf.c
 int
 main(void)
 {
-	char *buf;
-	char *tmp = "Hi";
+	char *tmp = "y";
 
-	(void) asprintf(&buf, "%s\n", tmp);
+	(void) asprintf(NULL, "%s\n", tmp);
 
 	return 0;
 }
@@ -93,12 +122,43 @@ $cc -o /tmp/checkasprintf /tmp/checkasprintf.c > /dev/null 2>&1
 if [ $? -ne 0 ] ; then
   echo "no"
   needasprintf="portable/asprintf.o"
+  cppasprintf="-DNEED_ASPRINTF"
 else
   echo "yes"
 fi
 
-rm -f /tmp/checkasprintf /tmp/checkasprintf.c
+rm -f /tmp/checkasprintf /tmp/checkasprintf.c checkasprintf.o
 
+printf "Checking for __progname... "
+
+cat << EOF > /tmp/checkprogname.c
+/* This file generated by oyacc configure script.  */
+
+#include <stdio.h>
+
+extern char *__progname;
+
+int
+main(void)
+{
+	(void) fprintf(stderr, "%s\n", __progname);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkprogname /tmp/checkprogname.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+  echo "no"
+  cppprogname="-DNEED_PROGNAME"
+else
+  echo "yes"
+fi
+
+rm -f /tmp/checkprogname /tmp/checkprogname.c checkprogname.o
+
+echo ""
 echo "Program will be installed as $yaccoroyacc."
 echo "Now type 'make' to build."
 
@@ -109,29 +169,22 @@ elif [ "x$os" = "xBitrig" ] ; then
   cflags="-O2 -pipe -Wall"
 elif [ "x$os" = "xFreeBSD" ] ; then
   cflags="-O2 -pipe -Wall -D__dead=\"__dead2\""
-  objs="portable/reallocarray.o"
 elif [ "x$os" = "xNetBSD" ] ; then
   cflags="-O2 -pipe -Wall"
-  objs="portable/reallocarray.o"
 elif [ "x$os" = "xDragonFly" ] ; then
   cflags="-O2 -pipe -Wall -D__dead=\"__dead2\""
 elif [ "x$os" = "xDarwin" ] ; then
   cflags="-O2 -pipe -Wall -D__dead=\"__attribute__((__noreturn__))\""
-  objs="portable/reallocarray.o"
 elif [ "x$os" = "xLinux" ] ; then
   cflags="-O2 -pipe -Wall -D__dead=\"__attribute__((__noreturn__))\""
-  objs="portable/reallocarray.o portable/strlcpy.o"
 elif [ "x$os" = "xSunOS" ] ; then
   cflags="-O2 -pipe -D__dead=\"\""
-  objs="portable/reallocarray.o"
 elif [ "x$os" = "xAIX" ] ; then
   cflags="-O3 -qstrict -qro -qroconst -D__dead=\"\""
-  objs="portable/reallocarray.o portable/strlcpy.o"
 else
   os=`uname -s | cut -c 1-6`
   if [ "x$os" = "xCYGWIN" ] ; then
     cflags="-O2 -Wall -D_GNU_SOURCE -D__dead=\"__attribute__((__noreturn__))\""
-    objs="portable/reallocarray.o"
   else
     echo "Unknown operating system, please add the OS to this script"
     echo "and submit a pull request to https://github.com/ibara/yacc"
@@ -143,7 +196,7 @@ cat << EOF > Makefile
 # This Makefile was generated by configure.
 
 CC=	$cc
-CFLAGS=	$cflags
+CFLAGS=	$cflags $cppreallocarray $cppstrlcpy $cppasprintf $cppprogname
 
 PREFIX=	/usr/local
 BINDIR=	\${PREFIX}/bin
@@ -152,7 +205,7 @@ MANDIR=	\${PREFIX}/man/man1
 PROG=	$yaccoroyacc
 OBJS=	closure.o error.o lalr.o lr0.o main.o mkpar.o output.o reader.o \\
 	skeleton.o symtab.o verbose.o warshall.o \\
-	$objs $needasprintf
+	$needreallocarray $needstrlcpy $needasprintf
 
 all: \${OBJS}
 	\${CC} \${LDFLAGS} -o \${PROG} \${OBJS}
