Improved asprintf() routine. Much improved configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,10 +2,43 @@
 # This configure script written by Brian Callahan <bcallah@devio.us>
 # and released into the Public Domain.
 
+if [ "x$CC" != "x" ] ; then
+  cc="$CC"
+  /usr/bin/which $cc > /dev/null 2>&1
+  if [ $? -ne 0 ] ; then
+    echo "C compiler $cc not found."
+    exit 1
+  fi
+else
+  /usr/bin/which cc > /dev/null 2>&1
+  if [ $? -eq 0 ] ; then
+    cc="cc"
+  else
+    /usr/bin/which gcc > /dev/null 2>&1
+    if [ $? -eq 0 ] ; then
+      cc="gcc"
+    else
+      /usr/bin/which clang > /dev/null 2>&1
+      if [ $? -eq 0 ] ; then
+	cc="clang"
+      else
+	/usr/bin/which pcc > /dev/null 2>&1
+	if [ $? -eq 0 ] ; then
+	  cc="pcc"
+	else
+	  echo "No C compiler found."
+	  exit 1
+	fi
+      fi
+    fi
+  fi
+fi
+
 printf "Checking for a program named yacc... "
-cat << EOF > /tmp/oyaccconfig.y
+
+cat << EOF > /tmp/checkyacc.y
 %{
-/* This is a test.  */
+/* This file generated by oyacc configure script.  */
 %}
 
 %%
@@ -21,24 +54,53 @@ main(void)
 	return 0;
 }
 EOF
-yacc -o /dev/null /tmp/oyaccconfig.y > /dev/null 2>&1
+
+yacc -o /dev/null /tmp/checkyacc.y > /dev/null 2>&1
 
 if [ $? -eq 0 ] ; then
-echo "found"
-yaccoroyacc=oyacc
-fix=oyyfix
+  echo "yes"
+  yaccoroyacc=oyacc
+  fix=oyyfix
 else
-echo "not found"
-yaccoroyacc=yacc
-fix=yyfix
+  echo "no"
+  yaccoroyacc=yacc
+  fix=yyfix
 fi
 
-rm -f /tmp/oyaccconfig.y
+rm -f /tmp/checkyacc.y
+
+printf "Checking for asprintf... "
+
+cat << EOF > /tmp/checkasprintf.c
+/* This file generated by oyacc configure script.  */
+
+#include <stdio.h>
+
+int
+main(void)
+{
+	char *buf;
+	char *tmp = "Hi";
+
+	(void) asprintf(&buf, "%s\n", tmp);
+
+	return 0;
+}
+EOF
+
+$cc -o /tmp/checkasprintf /tmp/checkasprintf.c > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+  echo "no"
+  needasprintf="portable/asprintf.o"
+else
+  echo "yes"
+fi
+
+rm -f /tmp/checkasprintf /tmp/checkasprintf.c
 
 echo "Program will be installed as $yaccoroyacc."
 echo "Now type 'make' to build."
-
-cc="cc"
 
 os=`uname -s`
 if [ "x$os" = "xOpenBSD" ] ; then
@@ -57,15 +119,14 @@ elif [ "x$os" = "xDarwin" ] ; then
   cflags="-O2 -pipe -Wall -D__dead=\"__attribute__((__noreturn__))\""
   objs="portable/reallocarray.o"
 elif [ "x$os" = "xLinux" ] ; then
-  cc="gcc"
   cflags="-O2 -pipe -Wall -D__dead=\"__attribute__((__noreturn__))\""
   objs="portable/reallocarray.o portable/strlcpy.o"
 elif [ "x$os" = "xSunOS" ] ; then
-  cflags="-xO2 -D__dead=\"\""
-  objs="portable/asprintf.o portable/reallocarray.o"
+  cflags="-O2 -pipe -D__dead=\"\""
+  objs="portable/reallocarray.o"
 elif [ "x$os" = "xAIX" ] ; then
   cflags="-O3 -qstrict -qro -qroconst -D__dead=\"\""
-  objs="portable/asprintf.o portable/reallocarray.o portable/strlcpy.o"
+  objs="portable/reallocarray.o portable/strlcpy.o"
 else
   os=`uname -s | cut -c 1-6`
   if [ "x$os" = "xCYGWIN" ] ; then
@@ -91,7 +152,7 @@ MANDIR=	\${PREFIX}/man/man1
 PROG=	$yaccoroyacc
 OBJS=	closure.o error.o lalr.o lr0.o main.o mkpar.o output.o reader.o \\
 	skeleton.o symtab.o verbose.o warshall.o \\
-	$objs
+	$objs $needasprintf
 
 all: \${OBJS}
 	\${CC} \${LDFLAGS} -o \${PROG} \${OBJS}
